### ISSUE TITLE
2024-12: EMF Forms 1.27 with DSL Developer package: LinkageError 

### ISSUE THREAD

**Issue by schauervalidas** [eclipse-packaging/packages#257]
Steps to reproduce:

1. Install Eclipse DSL Developer package with Eclipse installer on windows with release 2024-12
2. Install EMF Forms SDK from update site 
3. Invoke "New View Model" wizard
4. The following exception is thrown and the view editor is not opened:
5. Eclipse Commiter package 2024-12 works as expected with EMF Forms SDK 1.27

```eclipse.buildId=4.34.0.20241128-0756
java.version=22.0.2
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.dsl.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.dsl.product -data ----



org.eclipse.ui
Error
Tue Dec 10 18:52:23 CET 2024
Unhandled event loop exception



java.lang.LinkageError: loader constraint violation for class org.eclipse.emf.ecp.view.internal.editor.handler.SelectEcorePage: when selecting overriding method 'void org.eclipse.emf.ecp.view.internal.editor.handler.SelectEcorePage.createControl(org.eclipse.swt.widgets.Composite)' the class loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @2de41cb4 of the selected method's type org.eclipse.emf.ecp.view.internal.editor.handler.SelectEcorePage, and the class loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @6d2e3627 for its super type org.eclipse.jface.wizard.WizardPage have different Class objects for the type org.eclipse.swt.widgets.Composite used in the signature (org.eclipse.emf.ecp.view.internal.editor.handler.SelectEcorePage is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @2de41cb4, parent loader 'platform'; org.eclipse.jface.wizard.WizardPage is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @6d2e3627, parent loader 'platform')
  at org.eclipse.emf.ecp.view.model.presentation.ViewModelWizard.addPages(ViewModelWizard.java:218)
  at org.eclipse.jface.wizard.WizardSelectionPage.getNextPage(WizardSelectionPage.java:121)
  at org.eclipse.ui.internal.dialogs.WorkbenchWizardSelectionPage.getNextPage(WorkbenchWizardSelectionPage.java:98)
  at org.eclipse.jface.wizard.WizardDialog.nextPressed(WizardDialog.java:915)
  at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:470)
  at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
  at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
  at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:265)
  at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
  at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4404)
  at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1173)
  at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4202)
  at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3790)
  at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
  at org.eclipse.jface.window.Window.open(Window.java:799)
  at org.eclipse.ui.internal.handlers.WizardHandler$New.executeHandler(WizardHandler.java:261)
  at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:279)
  at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:277)
  at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:98)
  at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.base/java.lang.reflect.Method.invoke(Method.java:580)
  at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
  at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:299)
  at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:233)
  at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:174)
  at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:165)
  at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
  at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
  at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:204)
  at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:385)
  at org.eclipse.ui.internal.actions.CommandAction.runWithEvent(CommandAction.java:141)
  at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:581)
  at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:415)
  at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
  at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4404)
  at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1173)
  at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4202)
  at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3790)
  at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
  at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
  at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
  at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
  at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:663)
  at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
  at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:570)
  at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
  at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:178)
  at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
  at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
  at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
  at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
  at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
  at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.base/java.lang.reflect.Method.invoke(Method.java:580)
  at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
  at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
  at org.eclipse.equinox.launcher.Main.run(Main.java:1481)

```

![grafik](https://github.com/user-attachments/assets/9e171cf8-a47e-499d-ad9c-b21b1262f2cf)

**Comment by merks** [comment]
EMF Forms is no longer part of SimRel:

https://github.com/eclipse-simrel/simrel.build/pull/315

It's  strange error, but that's not something we can fix in the eclipse-packaging project.

You'll need to contact the ECP team, but as I understand it, they are not producing new releases:

https://projects.eclipse.org/projects/modeling.ecp/

**Comment by ruspl-afed** [comment]
> You'll need to contact the ECP team, but as I understand it, they are not producing new releases:

Hello @merks 

You are right, ECP is not the part of SimRel anymore. 
But this very problem is not about SimRel but rather about EPP: it does work for Committers package and does not for DSL package.
This may indicate a hidden trouble with DSL package configuration.

FYI:   @eneufeld @jfaltermeier @JonesHelming

**Comment by merks** [comment]
It’s not been tested to work with any package and it’s two years old. Someone else will need to investigate why it doesn’t work. I don’t expect the problem can be fixed by changing anything in any package but rather that ecp has some incompatibility with something in dsl package. Or maybe some rap/rwt thing got accidentally installed.

**Comment by ruspl-afed** [comment]
ok, I created [an issue for ECP](https://github.com/eclipse-ecp/org.eclipse.emf.ecp.core/issues/118)
